// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfd4R22VePxzblXb2STBN2Hhm591aW80k',
    appId: '1:144448000434:web:a7887b13b796af41fcd4ab',
    messagingSenderId: '144448000434',
    projectId: 'fcm-demo-a07bd',
    authDomain: 'fcm-demo-a07bd.firebaseapp.com',
    storageBucket: 'fcm-demo-a07bd.firebasestorage.app',
    measurementId: 'G-KM43R0HMWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Ie6t-rv3PjcvSjM9Lt8oYUZGrS9Z3Tg',
    appId: '1:144448000434:android:075a111cbaecdf73fcd4ab',
    messagingSenderId: '144448000434',
    projectId: 'fcm-demo-a07bd',
    storageBucket: 'fcm-demo-a07bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pRpCjAp7bx0Le8eiKpyvTVev0lNP2yc',
    appId: '1:144448000434:ios:220a62511251c9d2fcd4ab',
    messagingSenderId: '144448000434',
    projectId: 'fcm-demo-a07bd',
    storageBucket: 'fcm-demo-a07bd.firebasestorage.app',
    iosBundleId: 'com.example.qrScanGenerateFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0pRpCjAp7bx0Le8eiKpyvTVev0lNP2yc',
    appId: '1:144448000434:ios:220a62511251c9d2fcd4ab',
    messagingSenderId: '144448000434',
    projectId: 'fcm-demo-a07bd',
    storageBucket: 'fcm-demo-a07bd.firebasestorage.app',
    iosBundleId: 'com.example.qrScanGenerateFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfd4R22VePxzblXb2STBN2Hhm591aW80k',
    appId: '1:144448000434:web:507b38c4314f77e6fcd4ab',
    messagingSenderId: '144448000434',
    projectId: 'fcm-demo-a07bd',
    authDomain: 'fcm-demo-a07bd.firebaseapp.com',
    storageBucket: 'fcm-demo-a07bd.firebasestorage.app',
    measurementId: 'G-YQ6S5VRJ5H',
  );
}
